---
title       : Pitch Deck
subtitle    : Online Financial KPI Tracker
author      : Alex Lee
job         : 
framework   : html5slides        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Financial Key Performance Indicators: Online Dashboard

We are introducing a new, online, financial management oversight tool to track our company's performance, built in R.

What this tool offers:
* Live financial ratio calculation
* User-defined alert thresholds
* Accessible anywhere with an internet connection
* Customizable in R without web development knowledge

Where to find it:
* Online at: https://cs79.shinyapps.io/Financial-KPI-Tool/

--- .class #id 

## What Metrics are Covered?

By default, this online tool supports:
* Current Ratio: $$Current Liabilities / Current Assets$$
* Quick Ratio: $$Current Assets ex Inventory / Current Liabilities$$
* Working Capital Ratio: $$Current Assets / Current Liabilities$$
* Debt Ratio: $$Liabilities / Assets$$

By virtue of being written in R with Shiny, it is easily extensible to cover other metrics as needed by management.

--- .class #id

## How it Works: Example in R

an example of how the code runs

--- .class #id

## What else should I know?

can track multiple metrics at once; accessible online from anywhere so you don't need a spreadsheet

--- .class #id 

## hope you enjoy

a;lsjgsldkghj